import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "../components/SideBar";
import Footer from "../components/Footer";
import GitHubButton from "react-github-btn";
import { Analytics } from '@vercel/analytics/react'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zain Tech Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" data-theme="forest">
      <head>
        <title>{metadata.title as React.ReactNode}</title>
      </head>
      <body>
        <div className="flex flex-col h-screen justify-between">
          <header>
          </header>
          <main>
            <SideBar />
            {children}
            <Analytics />
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
